# Instalando Dependências (Numpy)

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
  Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl (12.5 MB)


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Usando Numpy no Python

In [7]:
import numpy as np
# Diferença entre listas tradicionais e o array numpy
lista_notas = [8,9,2,7,4,5,10]
for nota in lista_notas:
    print (nota / 2)

4.0
4.5
1.0
3.5
2.0
2.5
5.0


# Operação Vetorizada

In [11]:
array_notas = np.array([8,9,2,7,4,5,10])
print(array_notas / 2)
print(array_notas * 2)
print(array_notas - 2)

[4.  4.5 1.  3.5 2.  2.5 5. ]
[16 18  4 14  8 10 20]
[6 7 0 5 2 3 8]


In [13]:
produtos = np.array(["GTA VI", "CG 160", "Vingadores Donesday"])
precos = np.array([350, 22000, 30])
quantidade = np.array([12, 10, 20])

print(precos * quantidade)

[  4200 220000    600]


# Filtro Booleano (true or false)

In [26]:
array_numeros = np.array ([52, 45, 68, 93, 40, 25, 27])

filtro_valores = array_numeros > 50

array_numeros[filtro_valores]

#filtrando pares
filtro_valores = array_numeros % 2 == 0
print(array_numeros[filtro_valores])

[52 68 40]


In [39]:
#É ano novo na Fabprog e o Departamento Pessoal precisa calcular o dissídio do ano que vem (aumento de salário), esse aumento será de 10% (1.1) na folha de todos os funcionários.**

array_salarios = np.array([2500, 3000, 1300, 7000, 8500, 4000, 5000])

# O valor 1.1 equivale a 10% do salario
print(array_salarios *1.1)

[2750. 3300. 1430. 7700. 9350. 4400. 5500.]


In [40]:
#Uma empresa de engenharia possuí as dimensões das peças que irão fabricar diferentes reservatórios, o engenheiro responsável quer calcular o volume dessas peças de formato cúbico.**

#base [2, 1.5, 4, 7, 8]

#largura [3, 5, 2, 3, 3]

#altura [1, 6, 7, 9, 5]

#Calcule o volume de cada peça montada, volume de cubos (multiplicação de todos os lados)

array_base = np.array([2, 1.5, 4, 7, 8])
array_largura = np.array([3, 5, 2, 3, 3])
array_altura = np.array([1, 6, 7, 9, 5])

print(f"O vulume das peças é: {array_base * array_largura * (array_altura)}")



O vulume das peças é: [  6.  45.  56. 189. 120.]
